export default {
  font: {
    quicksand: 'Quicksand, sans-serif',
    heebo: 'Heebo, sans-serif',
    thin: 100,
    light: 300,
    regular: 400,
    bold: 600,
  },
  sizes: {
    xsmall: '1.2rem',
    small: '1.4rem',
    medium: '1.6rem',
    large: '1.8rem',
    xlarge: '2rem',
    xxlarge: '2.8rem',
  },
  spacings: {
    minimum: '0.2rem',
    xxsmall: '0.8rem',
    xsmall: '1.6rem',
    small: '2.4rem',
    medium: '3.2rem',
    large: '4.0rem',
    xlarge: '4.8rem',
    xxlarge: '5.6rem',
  },
  layers: {
    base: 10,
    menu: 20,
    overlay: 30,
  },
  transition: {
    default: '0.3s ease-in-out',
    fast: '0.1s ease-in-out',
  },
  colors: {
    primary: '#743dbf',
    secondary: '#19cdbf',
    gradient: '82deg, #39e6d7 0%, #19cdbf 100%',
    light: '#f1ebf9',
    black: '#212529',
    white: '#fff',
  },
} as const;
